# Set platform to iOS 13.0
platform :ios, '13.0'

# CocoaPods analytics sends network stats. If you want to disable this, uncomment the next line:
# cocoapods_disable_analytics

# Load Flutter pod helper scripts
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
